services:
  blog-app:
    image: kushal0107/blog-app:build-d9e82b9a82a1ab5165f0fc45ed3da224409d8dcb
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8080
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - blog-network
      - caddy-proxy_shared-net
networks:
  blog-network:
    driver: overlay
  caddy-proxy_shared-net:
    external: true
